module GreekCities
  module Cities
    AIT = [
      ['Αγρίνιο', 'agrinio-AIT'],
      ['Μεσολόγγι', 'mesologgi-AIT'],
      ['Αγγελόκαστρο', 'aggelokastro-AIT'],
      ['Αγία Βαρβάρα Βόνιτσας', 'ag-varvara-vonitsas-AIT'],
      ['Αγία Παρασκευή Παναιτωλικού', 'ag-paraskevi-panaitolikou-AIT'],
      ['Αγία Σοφία', 'ag-sofia-AIT'],
      ['Αγία Τριάδα Βάλτου', 'ag-triada-valtou-AIT'],
      ['Άγιοι Θεόδωροι Κεχρινιάς', 'ag-theodoroi-kehrinias-AIT'],
      ['Άγιος Ανδρέας', 'ag-andreas-AIT'],
      ['Άγιος Βλάσιος Χαλκιόπουλων', 'ag-vlasios-halkiopoulon-AIT'],
      ['Άγιος Γεώργιος Καλυβίων', 'ag-georgios-kalivion-AIT'],
      ['Άγιος Γεώργιος Μεσολογγίου', 'ag-georgios-mesologgiou-AIT'],
      ['Άγιος Γεώργιος Παλαιοκαρυάς', 'ag-georgios-palaiokarias-AIT'],
      ['Άγιος Δημήτριος Ναυπακτίας', 'ag-dimitrios-naupaktias-AIT'],
      ['Άγιος Ηλίας Μεσολογγίου', 'ag-ilias-mesologgiou-AIT'],
      ['Άγιος Θεόδωρος Κοκκινόβρυσης', 'ag-theodoros-kokkinovrisis-AIT'],
      ['Άγιος Θωμάς', 'ag-thomas-AIT'],
      ['Άγιος Ιωάννης Ρηγανάς', 'ag-ioannis-riganas-AIT'],
      ['Άγιος Κωνσταντίνος', 'ag-konstantinos-AIT'],
      ['Άγιος Νικόλαος Βόνιτσας', 'ag-nikolaos-vonitsas-AIT'],
      ['Άγιος Νικόλαος Τριχωνίδας', 'ag-nikolaos-trihonidas-AIT'],
      ['Άγιος Πολύκαρπος', 'ag-polikarpos-AIT'],
      ['Άγιος Στέφανος', 'ag-stefanos-AIT'],
      ['Άγιος Συμεών', 'ag-symeon-AIT'],
      ['Αγράμπελα', 'agrampela-AIT'],
      ['Αγραφορράχη', 'agraforrahi-AIT'],
      ['Αγραφορράχη', 'agraforrahi-AIT'],
      ['Αγριλιά', 'agrilia-AIT'],
      ['Αετόπετρα', 'aetopetra-AIT'],
      ['Αετός', 'aetos-AIT'],
      ['Αιτωλικό', 'aitoliko-AIT'],
      ['Άκρες', 'akres-AIT'],
      ['Άκτιο', 'aktio-AIT'],
      ['Αλευράδα', 'alevrada-AIT'],
      ['Αλώνια Σπολάιτας', 'alonia-spolaitas-AIT'],
      ['Αμβρακία', 'amvrakia-AIT'],
      ['Αμοργιανοί', 'amorgianoi-AIT'],
      ['Αμπελάκι', 'ampelaki-AIT'],
      ['Αμπελακιώτισσα', 'ampelakiotissa-AIT'],
      ['Αμπέλια Κοκκινόβρυσης', 'ampelakia-kokkinovrisis-AIT'],
      ['Αμπέλια Τριχωνίδας', 'ampelia-trihonidas-AIT'],
      ['Αμφιλοχία', 'amfilohia-AIT'],
      ['Αμφιλοχικό Άργος', 'amfilohiko-argos-AIT'],
      ['Αναβρυτή', 'anavriti-AIT'],
      ['Ανάληψη', 'analipsi-AIT'],
      ['Ανοιξιάτικο', 'anoixiatiko-AIT'],
      ['Αντίρριο', 'antirrio-AIT'],
      ['Άνω Άγιος Βλάσιος', 'ano-agios-vlasios-AIT'],
      ['Άνω Βλοχός', 'ano-vlohos-AIT'],
      ['Άνω Κεράσοβο', 'ano-kerasovo-AIT'],
      ['Άνω Κουδούνι', 'ano-koudouni-AIT'],
      ['Άνω Μούσουρα', 'ano-mousoura-AIT'],
      ['Άνω Χώρα', 'ano-hora-AIT'],
      ['Αράχοβα', 'arahova-AIT'],
      ['Αρχοντοχώρι', 'arhontohori-AIT'],
      ['Αστακός', 'astakos-AIT'],
      ['Αυλάκι', 'avlaki-AIT'],
      ['Βαλτί', 'valti-AIT'],
      ['Βαρειά', 'vareia-AIT'],
      ['Βαρετάδα', 'varetada-AIT'],
      ['Βαρκά', 'varka-AIT'],
      ['Βαρκό Πογωνιάς', 'varko-pogonias-AIT'],
      ['Βάρνακας', 'varnakas-AIT'],
      ['Βασιλόπουλο', 'vasilopoulo-AIT'],
      ['Βελβίνα', 'velvina-AIT'],
      ['Βελούχι', 'velouhi-AIT'],
      ['Βομβοκού', 'vomvokou-AIT'],
      ['Βόνιτσα', 'vonitsa-AIT'],
      ['Βρουβιανά', 'vrouviana-AIT'],
      ['Γαβαλού', 'gavalou-AIT'],
      ['Γαβρολίμνη', 'gavrolimni-AIT'],
      ['Γαλατάς', 'galatas-AIT'],
      ['Γέφυρα Μπανιά', 'gefira-mpania-AIT'],
      ['Γιαννόπουλοι', 'giannopouloi-AIT'],
      ['Γιαννούζι', 'giannouzi-AIT'],
      ['Γούργουβλη', 'gourgouvli-AIT'],
      ['Γουριά', 'gouria-AIT'],
      ['Γουριώτισσα', 'gouriotissa-AIT'],
      ['Γραμματικού', 'grammatikou-AIT'],
      ['Γραμμένη Οξυά', 'grammeni-oxia-AIT'],
      ['Δάφνη Μεσολογγίου', 'dafni-mesologgiou-AIT'],
      ['Δάφνη Ναυπακτίας', 'dafni-naupaktias-AIT'],
      ['Δαφνιάς', 'dafnias-AIT'],
      ['Διαμανταίικα', 'diamantaiika-AIT'],
      ['Διπλάτανος', 'diplatanos-AIT'],
      ['Δογρή', 'dogri-AIT'],
      ['Δοκίμι Αγρινίου', 'dokimi-agriniou-AIT'],
      ['Δουναίικα', 'dounaiika-AIT'],
      ['Δρυμός', 'drimos-AIT'],
      ['Δρυμώνας', 'drimonas-AIT'],
      ['Ελαιόφυτο Τριχωνίδας', 'eleofito-trihonidas-AIT'],
      ['Ελατόβρυση', 'elatovrisi-AIT'],
      ['Ελατού', 'elatou-AIT'],
      ['Ελευθερία', 'eleutheria-AIT'],
      ['Ελληνικά', 'ellinika-AIT'],
      ['Εμπεσός', 'empesos-AIT'],
      ['Ευηνοχώρι', 'evinohori-AIT'],
      ['Ζεστή', 'zesti-AIT'],
      ['Ζευγαράκι Μεσολογγίου', 'zevgaraki-mesologgiou-AIT'],
      ['Ζευγαράκι Τριχωνίδας', 'zevgaraki-trihonidas-AIT'],
      ['Θέρμο', 'thermo-AIT'],
      ['Θύαμος', 'thiamos-AIT'],
      ['Θύριο', 'thirio-AIT'],
      ['Καινούργιο', 'kainourio-AIT'],
      ['Καλλιθέα', 'kalithea-AIT'],
      ['Καλλονή', 'kalloni-AIT'],
      ['Καλούδι', 'kaloudi-AIT'],
      ['Καλύβια Τριχωνίδας', 'kalivia-trihonidas-AIT'],
      ['Καμαρούλα', 'kamaroula-AIT'],
      ['Κάμπος Αμπελακίου', 'kampos-ampelakiou-AIT'],
      ['Κάμπος Χούνης', 'kampos-hounis-AIT'],
      ['Κανδήλα', 'kandila-AIT'],
      ['Καραϊσκάκης', 'karaiskakis-AIT'],
      ['Καραμαναίικα', 'karamanaiika-AIT'],
      ['Καστράκι Βάλτου', 'kastraki-valtou-AIT'],
      ['Καστράκι Ναυπακτίας', 'kastraki-naupaktias-AIT'],
      ['Καστριώτισσα', 'kastriotissa-AIT'],
      ['Κατάφουρκο', 'katafourko-AIT'],
      ['Καταφύγι', 'katafigi-AIT'],
      ['Κατούνα', 'katouna-AIT'],
      ['Κατοχή', 'katohi-AIT'],
      ['Κάτω Αφροξυλιά', 'kato-afroxilia-AIT'],
      ['Κάτω Βασιλική', 'kato-vasiliki-AIT'],
      ['Κάτω Δάφνη', 'kato-dafni-AIT'],
      ['Κάτω Ελληνικά', 'kato-ellinika-AIT'],
      ['Κάτω Καλαβρούζα', 'kato-kalavrouza-AIT'],
      ['Κάτω Κεράσοβο', 'kato-kerasovo-AIT'],
      ['Κάτω Λαμπίρι', 'kato-lampiri-AIT'],
      ['Κάτω Μακρινού', 'kato-makrinou-AIT'],
      ['Κάτω Μαμουλάδα', 'kato-mamoulada-AIT'],
      ['Κάτω Ρέτσινα', 'kato-retsina-AIT'],
      ['Κάτω Τραγάνα', 'kato-tragana-AIT'],
      ['Κάτω Χρυσοβίτσα', 'kato-hrisovitsa-AIT'],
      ['Καψοράχη', 'kapsorahi-AIT'],
      ['Κελανίτης', 'kelanitis-AIT'],
      ['Κεραμίδι', 'keramidi-AIT'],
      ['Κεφαλόβρυσο Αιτωλικού', 'kefalovriso-aitolikou-AIT'],
      ['Κεφαλόβρυσος', 'kefalovrisos-AIT'],
      ['Κεχρινιά', 'kehrinia-AIT'],
      ['Κλεισορρεύματα', 'kleisorreumata-AIT'],
      ['Κλεπά', 'klepa-AIT'],
      ['Κοκκινόβρυση', 'kokkinovrisi-AIT'],
      ['Κοκκινοπύλια', 'kokkinopilia-AIT'],
      ['Κομποθέκλα', 'kompothekla-AIT'],
      ['Κομπωτή', 'kompoti-AIT'],
      ['Κονίσκα', 'koniska-AIT'],
      ['Κορπή', 'korpi-AIT'],
      ['Κουβαράς', 'kouvaras-AIT'],
      ['Κουλούρια', 'koulouria-AIT'],
      ['Κουτσοχέρι', 'koutsoheri-AIT'],
      ['Κόφτρα', 'koftra-AIT'],
      ['Κρεμαστά Συκιάς', 'kremasta-sikias-AIT'],
      ['Κρίκελλος', 'krikellos-AIT'],
      ['Κρύο Νερό', 'krio-nero-AIT'],
      ['Κρυονέρι', 'krioneri-AIT'],
      ['Κρυονέρια', 'krioneria-AIT'],
      ['Κυπάρισσος', 'kiparissos-AIT'],
      ['Κυψέλη Βάλτου', 'kipseli-valtou-AIT'],
      ['Λαγκάδι', 'lagkadi-AIT'],
      ['Λάσπες', 'laspes-AIT'],
      ['Λεπενού', 'lepenou-AIT'],
      ['Λεσίνι', 'lesini-AIT'],
      ['Λεύκα Αγρινίου', 'leuka-agriniou-AIT'],
      ['Λεύκα Ναυπακτίας', 'leuka-naupaktias-AIT'],
      ['Λευκό', 'leuko-AIT'],
      ['Λιβαδάκι', 'livadaki-AIT'],
      ['Λίμνη', 'limni-AIT'],
      ['Λιμνίτσα', 'limnitsa-AIT'],
      ['Λουτρά Μυρτιάς', 'loutra-mirtias-AIT'],
      ['Λουτράκι Κατούνας', 'loutraki-katounas-AIT'],
      ['Λυγιάς Νεοκάστρου', 'ligias-neokastrou-AIT'],
      ['Λυσιμάχεια', 'lisimaheia-AIT'],
      ['Μαγούλα', 'magoula-AIT'],
      ['Μακρινού', 'makrinou-AIT'],
      ['Μακύνεια', 'makineia-AIT'],
      ['Μαμουλάδα', 'mamoulada-AIT'],
      ['Μάνδρα', 'mandra-AIT'],
      ['Μαραθιάς', 'marathias-AIT'],
      ['Μάρμαρα Νεοχωρίου', 'marmara-neohoriou-AIT'],
      ['Μάστρο', 'mastro-AIT'],
      ['Ματαράγκα', 'mataragka-AIT'],
      ['Ματσούκι', 'matsouki-AIT'],
      ['Μαυροβορός', 'mavrovoros-AIT'],
      ['Μαχαιράς', 'mahairas-AIT'],
      ['Μεγάλη Χώρα', 'megali-hora-AIT'],
      ['Μέγας Δένδρος', 'megas-dendros-AIT'],
      ['Μενίδι', 'menidi-AIT'],
      ['Μεσάριστα', 'mesarista-AIT'],
      ['Μεσόκαμπος', 'mesokampos-AIT'],
      ['Μετόχι Αγίου Θωμά', 'metohi-ag-thoma-AIT'],
      ['Μολύκρειο', 'molikreio-AIT'],
      ['Μοναστηράκι', 'monastiraki-AIT'],
      ['Μπαμπαλιό', 'mpampalio-AIT'],
      ['Μπαμπίνη', 'mpampini-AIT'],
      ['Μπούζα', 'mpouza-AIT'],
      ['Μπούζι', 'mpouzi-AIT'],
      ['Μπούκκα', 'mpoukka-AIT'],
      ['Μυρτιά Τριχωνίδας', 'mirtia-trihonidas-AIT'],
      ['Μύτικας', 'mitikas-AIT'],
      ['Ναύπακτος', 'naupaktos-AIT'],
      ['Νέα Αβόρανη', 'nea-avorani-AIT'],
      ['Νέα Μαλεσιάδα', 'nea-malesiada-AIT'],
      ['Νέα Υδραγωγεία', 'nea-udragogia-AIT'],
      ['Νεάπολη', 'neapoli-AIT'],
      ['Νέο Αγρίδι', 'neo-agridi-AIT'],
      ['Νέο Χαλκιόπουλο', 'neo-halkiopoulo-AIT'],
      ['Νεόκαστρο', 'neokastro-AIT'],
      ['Νεοχώρι Μεσολογγίου', 'neohori-mesollogiou-AIT'],
      ['Νερομάνα', 'neromana-AIT'],
      ['Ξηροπήγαδο', 'xiropigado-AIT'],
      ['Όχθια', 'ohthia-AIT'],
      ['Παλαιά Φλωριάδα', 'palaia-floriada-AIT'],
      ['Παλαιοκαρυά Παραβόλας', 'palaiokaria-paravolas-AIT'],
      ['Παλαιομάνινα', 'palaiomanina-AIT'],
      ['Παλαιόπυργος', 'palaiopirgos-AIT'],
      ['Παλαιοχωράκι', 'palaiohoraki-AIT'],
      ['Παλαιοχώρι Σίμου', 'palaiohori-simou-AIT'],
      ['Πάλαιρος', 'palairos-AIT'],
      ['Παλιάμπελα Βάλτου', 'paliampela-valtou-AIT'],
      ['Παλιάμπελα Βόνιτσας', 'paliampela-vonitsas-AIT'],
      ['Πάμφιο', 'pamfio-AIT'],
      ['Παναιτώλιο', 'panaitolio-AIT'],
      ['Παντάνασσα', 'pontanassa-AIT'],
      ['Παππαδάτες', 'pappadates-AIT'],
      ['Παππαδάτος', 'pappadatos-AIT'],
      ['Παραβόλα', 'paravola-AIT'],
      ['Πατιόπουλο', 'patiopoulo-AIT'],
      ['Πεντάλοφο', 'pentalofo-AIT'],
      ['Περατιά', 'peratia-AIT'],
      ['Περδικάκι', 'perdikaki-AIT'],
      ['Περιθώρι', 'perithori-AIT'],
      ['Περίστα', 'perista-AIT'],
      ['Περιστέρι', 'peristeri-AIT'],
      ['Πετράλωνα', 'petralona-AIT'],
      ['Πετροχώρι', 'petrohori-AIT'],
      ['Πετρώνα', 'petrona-AIT'],
      ['Πηγάδια Περδικακίου', 'pigadia-perdikakiou-AIT'],
      ['Πιτσιναίικα', 'pitsinaiika-AIT'],
      ['Πλαγιά', 'plagia-AIT'],
      ['Πλατανιάς Τριχωνίδας', 'platanias-trihonidas-AIT'],
      ['Πλατανίτης', 'platanitis-AIT'],
      ['Πλάτανος Ναυπακτίας', 'platanos-naupaktias-AIT'],
      ['Πλάτανος Τριχωνίδας', 'platanos-trihonidas-AIT'],
      ['Πογωνιά', 'pogonia-AIT'],
      ['Ποδογορά', 'podogora-AIT'],
      ['Ποταμιά', 'potamia-AIT'],
      ['Ποταμούλα Μεσολογγίου', 'potamoula-mesologgiou-AIT'],
      ['Ποταμούλα Τριχωνίδας', 'potamoula-trihonidas-AIT'],
      ['Πρόδρομος', 'prodromos-AIT'],
      ['Προφήτης Ηλίας', 'profitis-ilias-AIT'],
      ['Πτελέα Ανοιξιάτικου', 'prelea-anoixiatiokou-AIT'],
      ['Πυργί', 'pirgi-AIT'],
      ['Ρίβιο', 'rivio-AIT'],
      ['Ρίγανη Μεσολογγίου', 'rigani-mesologgiou-AIT'],
      ['Ριγάνι', 'rigani-AIT'],
      ['Ρίζα', 'riza-AIT'],
      ['Σαράντη', 'saranti-AIT'],
      ['Σαργιάδα', 'sargiada-AIT'],
      ['Σαρδίνια', 'sardinia-AIT'],
      ['Σίμος', 'simos-AIT'],
      ['Σιταράλωνα', 'sitaralona-AIT'],
      ['Σιτόμενα', 'sitomena-AIT'],
      ['Σκάλα', 'skala-AIT'],
      ['Σκουρτού', 'skourtou-AIT'],
      ['Σκουτερά', 'skoutera-AIT'],
      ['Σκουτεσιάδα', 'skoutesiada-AIT'],
      ['Σπαρτιάς', 'spartias-AIT'],
      ['Σπάρτο', 'sparto-AIT'],
      ['Σταθάς', 'stathas-AIT'],
      ['Σταθμός Αγγελοκάστρου', 'stathmos-aggelokastrou-AIT'],
      ['Σταθμός Σταμνάς', 'stathmos-stamnas-AIT'],
      ['Σταμνά', 'stamna-AIT'],
      ['Στάνος', 'stanos-AIT'],
      ['Σταυρός', 'stauros-AIT'],
      ['Στενό', 'steno-AIT'],
      ['Στράτος', 'stratos-AIT'],
      ['Στρογγυλαίικα', 'stroggilaiika-AIT'],
      ['Στρογγυλοβούνι', 'stroggilovouni-AIT'],
      ['Στύλια', 'stilia-AIT'],
      ['Συκιά Βάλτου', 'sikia-valtou-AIT'],
      ['Συκιά Ναυπακτίας', 'sikia-naupaktias-AIT'],
      ['Συκούλα', 'sikoula-AIT'],
      ['Τερψιθέα', 'terpsithea-AIT'],
      ['Τραγάνα', 'tragana-AIT'],
      ['Τρελάγκαθα', 'trelagkatha-AIT'],
      ['Τριανταίικα', 'triantaiika-AIT'],
      ['Τρίκλινο', 'triklino-AIT'],
      ['Τρίκορφο', 'trikorfo-AIT'],
      ['Τριχώνιο', 'trihonio-AIT'],
      ['Τρύφος', 'trifos-AIT'],
      ['Φαμίλα', 'famila-AIT'],
      ['Φλωριάδα', 'floriada-AIT'],
      ['Φραγκαίικα', 'fragkaiika-AIT'],
      ['Φραγκόσκαλα', 'fragoskala-AIT'],
      ['Φραγκουλαίικα', 'fragoulaiika-AIT'],
      ['Φυτείες', 'fiteies-AIT'],
      ['Χαλίκι Μεσολογγίου', 'haliki-mesologgiou-AIT'],
      ['Χαλκιόπουλοι', 'halkiopouloi-AIT'],
      ['Χόμορη', 'homori-AIT'],
      ['Χούνη', 'houni-AIT'],
      ['Χρίσοβο', 'hrisovo-AIT'],
      ['Χρυσοβέργι', 'hrisovergi-AIT'],
      ['Χρυσόβιτσα Βόνιτσας', 'hrisovitsa-vonitsas-AIT'],
      ['Χρυσοβίτσα Τριχωνίδας', 'hrisovitsa-trihonidas-AIT'],
      ['Χρυσοπηγή', 'hrisopigi-AIT'],
      ['Χρυσορράχη', 'hrisorrahi-AIT'],
      ['Ψηλόβραχος', 'psilovrahos-AIT'],
    ].freeze.clone
  end
end
