module GreekCities
  module Cities
    ATTIKI = [
      ['Νέα Φιλαδέλφεια', 'nea-filadelpheia-ATT'],
      ['Χολαργός', 'holargos-ATT'],
      ['Δάφνη', 'dafni-ATT'],
      ['Κηφισιά', 'kifisia-ATT'],
      ['Μελίσσια', 'melissia-ATT'],
      ['Μοσχάτο', 'moshato-ATT'],
      ['Ψυχικό', 'psihiko-ATT'],
      ['Πεύκη', 'peuki-ATT'],
      ['Αργυρούπολη', 'argiroupoli-ATT'],
      ['Αγιοι Ανάργυροι', 'ag-anargiroi-ATT'],
      ['Αθήνα', 'athina-ATT'],
      ['Βύρωνας', 'vironas-ATT'],
      ['Καλλιθέα', 'kalithea-ATT'],
      ['Καισαριανή', 'kaisariani-ATT'],
      ['Ηράκλειο', 'irakleio-ATT'],
      ['Ηλιούπολη', 'ilioupoli-ATT'],
      ['Ζωγράφου', 'zografou-ATT'],
      ['Γαλάτσι', 'galatsi-ATT'],
      ['Γαλάτσι', 'galatsi-ATT'],
      ['Βριλήσσια', 'vrilissia-ATT'],
      ['Μαρούσι', 'marousi-ATT'],
      ['Άλιμος', 'alimos-ATT'],
      ['Αιγάλεω', 'aigaleo-ATT'],
      ['Ίλιο', 'ilio-ATT'],
      ['Άγιος Δημήτριος', 'ag-dimitrios-ATT'],
      ['Αγία Παρασκευή', 'ag-paraskevi-ATT'],
      ['Αγία Βαρβάρα', 'ag-varvara-ATT'],
      ['Γλυφάδα', 'glifada-ATT'],
      ['Πετρούπολη', 'petroupoli-ATT'],
      ['Χαλάνδρι', 'halandri-ATT'],
      ['Χαϊδάρι', 'haidari-ATT'],
      ['Περιστέρι', 'peristeri-ATT'],
      ['Παλαιό Φάληρο', 'palaio-faliro-ATT'],
      ['Νέα Ιωνία', 'nea-ionia-ATT'],
      ['Μεταμόρφωση', 'metamorfosi-ATT'],
      ['Νέα Σμύρνη', 'nea-smirni-ATT'],
      ['Κερατσίνι', 'keratsini-ATT'],
      ['Νίκαια', 'nikaia-ATT'],
      ['Γαλατάς', 'galatas-ATT'],
      ['Κύθηρα', 'kithira-ATT'],
      ['Σαλαμίνα', 'salamina-ATT'],
      ['Αγκίστρι', 'agkistri-ATT'],
      ['Πειραιάς', 'peiraias-ATT'],
      ['Πέραμα', 'perama-ATT'],
      ['Κορυδαλλός', 'koridallos-ATT'],
      ['Αίγινα', 'aigina-ATT'],
      ['Σπέτσες', 'spetses-ATT'],
      ['Πόρος', 'poros-ATT'],
      ['Υδρα', 'udra-ATT'],
      ['Ωρωπός', 'oropos-ATT'],
      ['Μαραθώνας', 'marathonas-ATT'],
      ['Ραφήνα', 'rafina-ATT'],
      ['Αγιος Στέφανος', 'ag-stefanos-ATT'],
      ['Αχαρνές', 'aharnes-ATT'],
      ['Γέρακας', 'gerakas-ATT'],
      ['Παιανία', 'paiania-ATT'],
      ['Σπάτα', 'spata-ATT'],
      ['Λαύριο', 'lavrio-ATT'],
      ['Καλύβια', 'kalivia-ATT'],
      ['Βούλα', 'voula-ATT'],
      ['Μαρκόπουλο', 'markopoulo-ATT'],
      ['Κορωπί', 'koropi-ATT'],
      ['Κεραταία', 'κerataia-ATT'],
      ['Ελευσίνα', 'eleusina-ATT'],
      ['Μάνδρα', 'mandra-ATT'],
      ['Μέγαρα', 'megara-ATT'],
      ['Ασπρόπυργος', 'aspropirgos-ATT']
    ].freeze.clone
  end
end
